services:
  influxdb:
    image: influxdb:2.7
    container_name: gonetwatch_influx
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: always

volumes:
  influxdb_data:
  influxdb_config: