targets:
    - name: Example Com HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://example.com
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Iana Org HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://iana.org
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Github Com HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://github.com
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Go Dev HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://go.dev
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Gitlab Com HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://gitlab.com
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Cloudflare Com HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://cloudflare.com
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Wikipedia Org HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://wikipedia.org
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Mozilla Org HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://mozilla.org
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Nginx Org HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://nginx.org
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
    - name: Ubuntu Com HTTP HEAD
      type: http-head
      protocol: http-head
      address: https://ubuntu.com
      interval_sec: 60
      timeout_sec: 5
      retries: 0
      retry_delay_ms: 300
      resolver: ""
      expected_statuses: []
influxdb:
    url: http://influxdb:8086
    token: INFLUX_TOKEN
    org: gonetwatch
    bucket: network_metrics
telegram:
    bot_token: ""
    chat_ids: []
